version: "3.8"

services:
  kafka-server:
    image: bitnami/kafka:latest
    container_name: kafka-server
    restart: always
    hostname: kafka-server
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-server:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 9092:9092
    networks:
      - app-tier

  kafka-connect:
    image: debezium/connect:2.4
    container_name: kafka-connect
    restart: always
    depends_on:
      - kafka-server
    environment:
      - BOOTSTRAP_SERVERS=kafka-server:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONNECT_PLUGIN_PATH=/kafka/connect,/usr/share/custom-plugins
      - CONNECT_REST_ADVERTISED_HOST_NAME=kafka-connect
      - CONNECT_REST_PORT=8083
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_LOG_LEVEL=INFO
    ports:
      - 8083:8083
    volumes: 
      - ./kafka-connect-plugins:/usr/share/custom-plugins
    networks:
      - app-tier

  meilisearch:
    image: getmeili/meilisearch:v1.2
    container_name: meilisearch
    restart: always
    ports:
      - "7700:7700"
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=masterKey
    volumes:
      - meili_data:/meili_data
    networks:
      - app-tier

  postgres:
    image: debezium/postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: cdc_user
      POSTGRES_PASSWORD: cdc_password
      POSTGRES_DB: adsonly
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  meili_data:
  postgres_data:
