name=meilisearch-sink-connector
connector.class=org.adsonly.MeilisearchSinkConnector
tasks.max=1
topics=products

meilisearch.host=http://localhost:7700
meilisearch.apiKey=your-api-key
meilisearch.index=products-index